language: node_js
node_js:
  - '12'

notifications:
  email:
    on_success: never
    on_failure: always

script: yarn build

deploy:
  provider: npm
  email: npm@jupiterone.io
  api_key:
    secure: "AyHamvWmMXXKYflWBL6K9OrZDn1AGP0o2am+podfH7lq40P3GtbWG42kyrZTdGVZ+bBLrNSSk8pbQQvetIVyBVs6Jc+z3IgadB5grV2FF5Krt2ZMVy5c61g4HE0IhIpGF60tGT1zmmHIjesUXTjuFJt6dWipOVqzWvEaK/A3TpKX3nkKFe7uzLI8r8xha32M27I6KyZ/yBKWFs5ZBlNbQx2EUpYvKQMJCClnrmmeREO+R0PQr8yyHaRm9JNKlFhzrimudoc9ZOwND0QyKwE83l7dpx6gYg3tYD3f13gEifA7WIz5FtCg8ZUR34bBsAXILBEQRbS07s5Xq0S+lj14s4W8m2sIHZgn2wUx4z6IaEOGJCVq0JgESRzZaOfuZoaukarthF7B+JWT+tc04VKnePuot2w2YHlDuks+VEEtKTboU62fEgtw5323lKRnK0j5TjJqhn67AuQrsDJfx1beGr90aoiFqB2A7Fwe7rOWZ3xypWNQLfKFi2EgYKPhx/fh8EZcYC48LyyLtUcuVvz9wcYMdAkfAdc3nBjDHEi5FU4VgP30RRdla++I/D1y3fWaez4E8tPsrsgBCzfYCtDZNB694qEnyfE7YQtVdEh2/NE1nYOh235QRlUXMRt2z4n0DMi/QTDfjeGBgk9vy4LCO3Jnja+gbRiAkB0JG4k1F1A="
  skip_cleanup: true
  on:
    tags: true
    branch: master
    repo: JupiterOne/graph-whois
    node: '12'
