openapi: 3.0.1
info:
  title: '@jupiterone/graph-whois'
  description: A JupiterOne managed integration for WHOIS data
  x-cortex-git:
    github:
      repository: JupiterOne/graph-whois
  x-cortex-owners:
    - type: group
      name: JupiterOne/integrations
  x-cortex-tag: '@jupiterone/graph-whois'
  x-cortex-service-groups:
    - tier-4
